### ISSUE TITLE
Incorrect debian version comparisons with tilde

### ISSUE THREAD

**Issue by mssalvatore** [memory/python-dpkg#3]
The tilde in debian versions sorts before anything else, meaning version 1.2.3-1~deb7u1 is less than 1.2.3-1. python-dpkg does not properly sort these versions.

The check here triggers an IndexError:
https://github.com/memory/python-dpkg/blob/dc88cfbbd0f052a6808f339486bf9b7e991c137c/pydpkg/__init__.py#L497

This index error is caught here:
https://github.com/memory/python-dpkg/blob/dc88cfbbd0f052a6808f339486bf9b7e991c137c/pydpkg/__init__.py#L513-L515

The assumption that since rev1 is longer than rev2 it is greater is not correct because of the tilde.

Below are some tests that can be added to `test_dpkg.py` to catch this error. I've also added a few other tests for completeness and to catch some other edge cases.

```diff
diff --git a/tests/test_dpkg.py b/tests/test_dpkg.py
index 2bec9b7..8dd1564 100644
--- a/tests/test_dpkg.py
+++ b/tests/test_dpkg.py
@@ -187,6 +187,9 @@ class DpkgVersionsTest(unittest.TestCase):
         self.assertEqual(Dpkg.compare_versions('0.0.9', '0.0.10'), -1)
         self.assertEqual(Dpkg.compare_versions('0.9.0', '0.10.0'), -1)
         self.assertEqual(Dpkg.compare_versions('9.0.0', '10.0.0'), -1)
+        self.assertEqual(Dpkg.compare_versions('1.2.3-1~deb7u1', '1.2.3-1'), -1)
+        self.assertEqual(Dpkg.compare_versions('2.7.4+reloaded2-13ubuntu1', '2.7.4+reloaded2-13+deb9u1'), -1)
+        self.assertEqual(Dpkg.compare_versions('2.7.4+reloaded2-13', '2.7.4+reloaded2-13+deb9u1'), -1)
 
         # greater than
         self.assertEqual(Dpkg.compare_versions('0.0.1-0', '0:0.0.0'), 1)
@@ -195,6 +198,9 @@ class DpkgVersionsTest(unittest.TestCase):
         self.assertEqual(Dpkg.compare_versions('0.0.9', '0.0.1'), 1)
         self.assertEqual(Dpkg.compare_versions('0.9.0', '0.1.0'), 1)
         self.assertEqual(Dpkg.compare_versions('9.0.0', '1.0.0'), 1)
+        self.assertEqual(Dpkg.compare_versions('1.2.3-1', '1.2.3-1~deb7u1'), 1)
+        self.assertEqual(Dpkg.compare_versions('2.7.4+reloaded2-13+deb9u1', '2.7.4+reloaded2-13ubuntu1'), 1)
+        self.assertEqual(Dpkg.compare_versions('2.7.4+reloaded2-13+deb9u1', '2.7.4+reloaded2-13'), 1)
 
         # unicode me harder
         self.assertEqual(Dpkg.compare_versions(u'2:0.0.44-1', u'2:0.0.44-nobin'), -1)
```

I haven't had the time to try and come up with a solution, but, as a reference, here's another pure-python implementation of version comparison: https://git.launchpad.net/review-tools/tree/reviewtools/debversion.py

**Comment by memory** [comment]
Oh wow, that's been there since the very beginning.  Thanks for spotting it; let me see if I can come up with a reasonable fix.

**Comment by memory** [comment]
Side-note, python-apt has...interesting opinions about your second test:

```
>>> apt.apt_pkg.version_compare('2.7.4+reloaded2-13ubuntu1', '2.7.4+reloaded2-13+deb9u1')
-182
>>> apt.apt_pkg.version_compare('2.7.4+reloaded2-13+deb9u1', '2.7.4+reloaded2-13ubuntu1')
182
```

**Comment by memory** [comment]
@mssalvatore do you want to try patching https://github.com/memory/python-dpkg/pull/4 into your environment and verify that it works correctly before I merge and release?

**Comment by mssalvatore** [comment]
@memory Sorry for the delay, the weekend was busy.

All my tests pass. Thanks!
